const route = [
    'dashboard',
    'dashboard-dark',
    'user-list',
    'broker-list',
    'request-list',
    'sub-user-list',
    'link-list',
    'sub-user-link-list',
    'carrier-sub-user-list',
    'carrier-sub-user-Link-list',
    'sub-user-fmcsas-list',
    'payment-history',
    'upcoming-subscriptions',
    'view-maintence',
    'cms-list',
    'manage-subscriptions',
    'faq-list',
    'contact-us',
    'chat',
    'general-notification',
    'user-notification',
    'notification-detail',
    'user-detail',
    'maintenance-request-list',
    'technical-guide-list',
    'faq-group-list',
    'technician-list',
    'live-chat',
]

export default route